.gitignore, public/index.php, routes/categoryRoutes.php, src/Controller/CategoryController.php, views/category/add.phtml, views/category/list.phtml
=> Adiciona o controller de categoria e suas views

.gitignore, src/Controller/AbstractController.php, views/_layouts/footer.phtml, views/_layouts/head.phtml
=> Configurando o template visual

views/advertisement/add.phtml
**📝 Descrição:**
Este PR adiciona a funcionalidade de cadastro de anúncios à aplicação. Foi criada uma nova página onde os anunciantes podem preencher e enviar informações para registrar um novo anúncio.
Principais mudanças:
* Criação da página de cadastro de anúncio
=> fet:add ad registration page

views/advertisement/list.phtml
fix #8 
- Adcionei a pagina de listar anuncios
=> Adcionar pagina de listar anuncios

views/advertisement/list.phtml
fix #22 
- Modifiquei o estilo da tela de listar anuncios
- E para exibição dos dados, fiz um forEachem um Array
=> style: modificar estilo da tela de listagem de anúncios

views/auth/login.phtml
=> Tela login

views/auth/login.phtml
adicionado link para recuperar senha
adicionado link para cadastrar
=> feat: login-links

views/user/profile.phtml
=> style: ajuste visual no card de perfil do usuário

views/user/list.phtml
=> inserido o layout padrao do projeto em Lista de anunciante

views/_layouts/head.phtml
=> Adicionando link de icons

views/category/list.phtml
=> feat: adicionar botão 'Adicionar Categoria'

docs/schema.md, src/Entity/Example.php
=> Criando entidade Example

routes/advertisementRoutes.php, routes/authRoutes.php, routes/userRoutes.php, src/Controller/AuthController.php, src/Controller/HomepageController.php, views/_layouts/navbar.phtml, views/auth/logout.phtml
=> Fix: Conserta links do menu

views/user/list.phtml
fix #45 
- Melhorada a organização visual da tabela de usuários
- Ajustado espaçamento e cores para melhor usabilidade
=> feat: atualiza tela de listagem de usuários com estilo Bootstrap

src/Entity/Review.php
=> feat: criado entidade review

src/Entity/AdvertiserPlan.php, src/Enum/AdvertiserPlanStatusEnum.php
=> feat: Implementa entidade AdvertiserPlan e status enum

src/Entity/Address.php
Fix #59 
Criação da entidade Address com os atributos de endereço padrão. A classe segue os padrões PSR e OOP definidos no projeto.
=> feat: criação da entidade Address

README.md, bin/doctrine, composer.json, composer.lock, doctrine.php, src/Entity/Category.php
=> Install and Config doctrine library

src/Entity/ContactInformation.php
=> Criando a entidade ContactInformation

src/Entity/AdvertiserPlan.php
=> Cria mapeamento da entidade AdvertiserPlan com ORM

src/Entity/Review.php
=> feact: Criado mapeamento da entidade Review com ORM

views/category/add.phtml
=> style: Melhorado estilo da tela de cadastrar categoria

views/_layouts/footer.phtml
=> refactor: Refatoração do arquivo "footer"

Makefile
=> Criando Makefile

src/Entity/Address.php
=> entity-address

routes/advertisementRoutes.php, routes/authRoutes.php, routes/categoryRoutes.php, routes/userRoutes.php
=> refactor: ajustar arquivos de rotas conforme issue #112

src/Service/ContactInformationService.php
=> Add Service ContactInformation

public/css/custom.css, views/_layouts/navbar.phtml, views/advertisement/add.phtml
=> refactor: Realizado melhorias do Navbar

src/Service/AdvertiserPlanService.php
=> Add service advertiserPlan

src/Service/CategoryService.php
=> Add service Category

public/css/custom.css, views/auth/login.phtml
=> Add modern login page with validation and password recovery modal

views/homepage/index.phtml
=> Realizado melhorias da tela principal

views/error/page-not-found.phtml
=> Realizado melhorias da tela de error

views/user/profile.phtml
=> Realizado melhoria na tela perfil

public/css/custom.css
=> refactor: custom update

views/advertisement/add.phtml
=> refactor: melhorado a tela de adicionar anuncios

public/css/custom.css, src/Controller/AbstractController.php, src/Controller/CategoryController.php, src/Entity/Category.php, src/Service/CategoryService.php, views/category/add.phtml, views/category/list-old.phtml, views/category/list.phtml
=> Listar e Cadastrar categoria

Makefile, bin/fixtures, src/Entity/Advertiser.php
=> feat: Adicionar coluna de password na entidade User

src/Controller/UserController.php, views/user/add.phtml
=> Create User using database

src/Controller/UserController.php, src/Entity/Advertiser.php, src/Service/AdvertiserService.php, views/user/list.phtml
=> Connect ad form

views/plan/add.phtml
=> feat: create plan form

src/Controller/AdvertiserPlanController.php
=> Add method
